services:
  eureka-server:
    image: kwa06001/server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices

  gateway:
    image: kwa06001/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  frontend:
    image: kwa06001/fe
    container_name: frontend
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  deploy:
    image: kwa06001/deploy
    container_name: deploy
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  user:
    image: kwa06001/user
    container_name: user
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

networks:
  microservices:
    driver: bridge

volumes:
  eureka-data: